### ISSUE TITLE
Ordem das frases não está igual ao do SLD

### ISSUE THREAD

**Issue by atilarec** [smartlaudos/slnuvem#10]
Quando estou no laudo do exame e seleciono usar um modelo a ordem das frases não está igual ao do SLD, e os IDs também eles já começaram do id 17.

**Comment by andersonbispo** [comment]
Resolvi a ordem. O fato do id começar do 17 é no filtro de modelos do tipo observação. Isto acontece porque os modelos do tipo observação e conclusão compartilham a mesma tabela. Então o tipo conclusão é do id 1 ao 16 e o tipo observação é do id 17 ao 32.
