### ISSUE TITLE
A opção de "Habilitar assinatura" está ficando habilitada mesmo quando não se tem uma imagem de assinatura adicionada.

### ISSUE THREAD

**Issue by valdenia** [smartlaudos/slnuvem#30]
Pré-condição: 
1. Estar logado 

Passos para reproduzir: 
1. Acessar a tela de "Novo Médico"
2. Preencher todos os campos obrigatórios
3. Selecionar a opção de "Habilitar assinatura" sem ter adicionado uma imagem ao campo de Assinatura
4. Clicar no botão "Salvar" 

Resultado atual: Cadastro salvo normalmente

Resultado esperado: O esperado é que a opção de "Habilitar assinatura" fica desabilitado enquanto não exista imagem de assinatura adicionada.

**Comment by danielgatis** [comment]
Esse é o comportamento esperado, pode habilitar/desabilitar a assinatura mesmo sem assinatura, essa validação não é necessária (quanto menos validação melhor).

**Comment by valdenia** [comment]
Esse comportamento "esperado" foi alinhado com os demais?
