### ISSUE TITLE
Campos para colocar em duas colunas

### ISSUE THREAD

**Issue by atilarec** [smartlaudos/slnuvem#35]
Filial:
 - email e telefone

Medico:
 - email e telefone

Paciente:
 - data de nascimento e sexo ; email e telefone

Exame: (deve mudar a ordem também, como abaixo)
 - data e clinica; medico e convênio; paciente e medico solicitante.
 - obs: medico e convenio devem ser obrigatórios

**Comment by danielgatis** [comment]
Apenas 1 coluna.
Unica exceção a essa regra são campos relacionados (crm / uf por exemplo).

mais aqui:
http://www.smashingmagazine.com/2011/11/08/extensive-guide-web-form-usability/

**Comment by atilarec** [comment]
Brojeto

Átila Bezerra
